# Generated by Django 3.2.4 on 2021-06-14 18:14

from datetime import timedelta

from django.db import migrations
from task.models import Homework


def add_homework_object(apps, schema_editor):
    Homework.objects.create(text="text", available_time=timedelta(1))


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_homework_object),
    ]
