# Generated by Django 3.2.4 on 2021-06-14 18:20

from django.db import migrations
from task.models import Student


def add_student_object(apps, schema_editor):
    Student.objects.create(first_name="StudentName", last_name="StudentSurname")


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0002_add_Homework_object"),
    ]

    operations = [
        migrations.RunPython(add_student_object),
    ]
