# Generated by Django 3.2.4 on 2021-06-14 18:47

from django.db import migrations
from task.models import Homework, Student


def add_homework_result_object(apps, schema_editor):
    homework = Homework.objects.get(pk=1)
    student = Student.objects.get(pk=1)
    homework_result = student.do_homework(homework=homework, solution="Solution")
    homework_result.save()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0003_add_Student_object"),
    ]

    operations = [migrations.RunPython(add_homework_result_object)]
