# Generated by Django 3.2.4 on 2021-06-14 19:44

from django.db import migrations
from task.models import Teacher


def add_teacher_object(apps, schema_editor):
    Teacher.objects.create(first_name="TeacherName", last_name="TeacherSurname")


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_add_HomeworkResult_object"),
    ]

    operations = [migrations.RunPython(add_teacher_object)]
